### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by GeoffreyEmery** [hypriot/blog#10]
Great site,
   Stumbled on this and its great. Wanted to subscribe to get your updates seems your misssing rss feed. Maybe think about adding one? https://gohugo.io/templates/rss/
   Cheers,
     G

**Comment by MathiasRenner** [comment]
@GeoffreyEmery Thank you for this requrest! RSS would definitely be a benefit. However, this is not high prioritized by us right now – any PR is welcome :-)

**Comment by GeoffreyEmery** [comment]
I posted the link to how you do it using your current implementation.. there is no way for me to remember to come back to this site without some kind of syndication maybe a email sign up?

**Comment by MathiasRenner** [comment]
For now, I suggest our twitter channel, where you will get all updates about new blog posts and more.
As long as there are not more people requesting this, this ticket has only low prio, sorry...

**Comment by GeoffreyEmery** [comment]
There isn't even a link to your twitter on that site just a FYI. I find twitters noise to be substantial to find and sort through things like this. But I figured out ill just watch this repo and if you update the blog github will tell me so that will have to do.
