### ISSUE TITLE
Missing latest deb packages

### ISSUE THREAD

**Issue by myoung34** [hypriot/blog#36]
There are download links for the latest deb releases of 1.10.3, etc but there aren't any for the 1.11 or 1.12 releases (of which there are SD card images)

**Comment by StefanScherer** [comment]
The 1.11 deb of docker-hypriot is in our packagecloud.io Schatzkiste: https://packagecloud.io/app/Hypriot/Schatzkiste/search?filter=all&q=docker-hypriot&dist=

The 1.12.1 and above is built directly by Docker and available in their apt repo.

We discontinue to add all debs as direct download links as we use the apt repos which makes it easier.

**Comment by myoung34** [comment]
Oops, I thought those corresponded to docker builds
