### ISSUE TITLE
Flannel pod creation no longer works

### ISSUE THREAD

**Issue by jcleira** [hypriot/blog#45]
First, let me thank you for the blog and the time that you spend on creating it!.

I spotted an error while installing the cluster related to the flannel pods creation.

You are using the master version here:

```bash
curl -sSL https://rawgit.com/coreos/flannel/master/Documentation/kube-flannel.yml | sed "s/amd64/arm/g" | kubectl create -f -
```

But on [this commit](https://github.com/coreos/flannel/commit/ee52b531b0c3ce81b3a08bc3a5dccf4d31476ecd) the image URL no longer includes the `amd64` tag, so the sed has no effect on it.

I'm on a rush right now and can't think on a good solution for a PR atm.

**Comment by reedy** [comment]
Looks like what you were worried about was reverted very soon after https://github.com/coreos/flannel/commit/ab5ec81a2dd6b98eaf41cccbfa6388216fefdeae

This can be closed as nothing to change

**Comment by jcleira** [comment]
:+1:
