### ISSUE TITLE
No wlan0 on RPI3 for 17.1

### ISSUE THREAD

**Issue by higstar** [hypriot/blog#70]
Similar to #60, and as mentioned by @dominikschubert "There is no wlan0 interface when running ifconfig on a clean HypriotOS install on Raspberry Pi 3".

**Comment by StefanScherer** [comment]
Hi @higstar, I've tried that today. You have to modify the `/boot/config.txt´ and change the UART setting to `enable_uart=0`.

UART is turned on by default to investigate the boot with an USB Serial cable and Raspberry Pi 3 uses either WiFi or UART on the same pins.

Let me know if you then can have your wireless RPi3 running.

**Comment by goughjt** [comment]
@higstar I was able to get wifi to work on boot with latest hypriotOS (1.7.1) and r-pi3. Please see https://github.com/hypriot/blog/issues/60#issuecomment-351239790.

**Comment by higstar** [comment]
Thanks @StefanScherer  and @goughjt it was as simple as that (which I have now confirmed).
I will put a pull request together with a comment in the user-data file, within the wifi section suggesting to check the uart in the config.txt.

**Comment by StefanScherer** [comment]
@higstar That‘s a very good idea. Looking forward to the PR :-)
