### ISSUE TITLE
Donation is not working

### ISSUE THREAD

**Issue by MiroslavMikus** [hypriot/blog#87]
Donation button from the readme.md points to https://liberapay.com/Hypriot/donate. There is an error message:
![image](https://user-images.githubusercontent.com/29312172/53267663-315afa00-36e4-11e9-9fa7-9e92d983c489.png)

So please double check your payment settings...

**Comment by MathiasRenner** [comment]
Thanks for your feedback! We added a Paypal account. Did this resolve the issue?

**Comment by MathiasRenner** [comment]
Now, you can pay with credit card and SEPA debit, too.

Please reopen if you encounter any more problems.
